sources:
  - name: CoinDesk
    url: https://www.coindesk.com/latest-crypto-news
    country: US
    credibility_score: 0.5
    article_url_patterns:
      - "/news/"
      - "/markets/"
      - "/policy/"
      - "/tech/"
      - "/coindesk-indices/"

  - name: CoinTelegraph
    url: https://cointelegraph.com/category/latest-news
    country: US
    credibility_score: 0.85
    article_url_patterns:
      - "/news/"
  
  - name: Decrypt
    url: https://decrypt.co/news
    country: US
    credibility_score: 0.7
    article_url_patterns:
      - "^/\\d+/"
  - name: beincrypto
    url: https://beincrypto.com/category/
    country: UK
    fetch_strategy: httpx
    credibility_score: 0.65
    article_url_patterns:
    - "^/[a-z0-9-]+/?$"
  - name: cryptonews
    url: https://cryptonews.com/news/
    country: UK
    fetch_strategy: httpx
    credibility_score: 0.65
    article_url_patterns:
      - "^/news/[a-z0-9-]+/?$"

  - name: blockworks
    url: https://blockworks.co/news
    country: UK
    fetch_strategy: httpx
    credibility_score: 0.65
    article_url_patterns:
      - "/news/"
  - name: utoday
    url: https://u.today
    country: UAE
    credibility_score: 0.7
    fetch_strategy: httpx
    article_url_patterns:
      - "^/[a-z0-9-]{15,}/?$"
  - name: coingape
    url: https://coingape.com/category/news/
    country: UAE
    credibility_score: 0.7
    fetch_strategy: httpx
    article_url_patterns:
      - "^/[a-z0-9-]{15,}/?$"

  - name: ambcrypto
    url: https://ambcrypto.com/category/new-news/
    country: INDIA
    credibility_score: 0.7
    fetch_strategy: httpx
    article_url_patterns:
      - "^/[a-z0-9-]{15,}/?$"
  - name: cryptotimes
    url: https://www.cryptotimes.io/all-news/
    country: INDIA
    credibility_score: 0.65
    fetch_strategy: httpx
    article_url_patterns:
      - "^/\\d{4}/\\d{2}/\\d{2}/[a-z0-9-]+/?$"      
  